export const sriLankaDistricts = [
  "Colombo",
  "Gampaha",
  "Kalutara",
  "Kandy",
  "Matale",
  "Nuwara Eliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  "Batticaloa",
  "Ampara",
  "Trincomalee",
  "Kurunegala",
  "Puttalam",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Monaragala",
  "Ratnapura",
  "Kegalle",
];

export const sriLankaCities: Record<string, string[]> = {
  Colombo: ["Colombo", "Dehiwala", "Moratuwa", "Kotte", "Kesbewa"],
  Gampaha: ["Negombo", "Gampaha", "Katunayake", "Wattala", "Ja-Ela"],
  Kalutara: ["Kalutara", "Panadura", "Beruwala", "Horana", "Matugama"],
  Kandy: ["Kandy", "Peradeniya", "Katugastota", "Gampola", "Pilimathalawa"],
  Matale: ["Matale", "Rattota", "Dambulla", "Ukuwela", "Nalanda"],
  "Nuwara Eliya": ["Nuwara Eliya", "Hatton", "Talawakele", "Ragala", "Lindula"],
  Galle: ["Galle", "Hikkaduwa", "Ambalangoda", "Baddegama", "Elpitiya"],
  Matara: ["Matara", "Weligama", "Dikwella", "Akuressa", "Kamburupitiya"],
  Hambantota: [
    "Hambantota",
    "Tangalle",
    "Tissamaharama",
    "Ambalantota",
    "Sooriyawewa",
  ],
  Jaffna: ["Jaffna", "Chavakachcheri", "Point Pedro", "Nallur", "Kopay"],
  Kilinochchi: ["Kilinochchi", "Pallai", "Karachchi", "Paranthan"],
  Mannar: ["Mannar", "Murunkan", "Pesalai", "Thalaimannar"],
  Vavuniya: ["Vavuniya", "Nedunkeni", "Cheddikulam", "Vavuniya South"],
  Mullaitivu: ["Mullaitivu", "Puthukkudiyiruppu", "Oddusuddan", "Thunukkai"],
  Batticaloa: ["Batticaloa", "Eravur", "Valachchenai", "Kattankudy", "Vakarai"],
  Ampara: ["Ampara", "Kalmunai", "Akkaraipattu", "Sammanthurai", "Uhana"],
  Trincomalee: ["Trincomalee", "Kinniya", "Kantalai", "Mutur", "Thampalakamam"],
  Kurunegala: [
    "Kurunegala",
    "Kuliyapitiya",
    "Pannala",
    "Narammala",
    "Polgahawela",
  ],
  Puttalam: ["Puttalam", "Chilaw", "Wennappuwa", "Nattandiya", "Anamaduwa"],
  Anuradhapura: [
    "Anuradhapura",
    "Mihintale",
    "Kekirawa",
    "Medawachchiya",
    "Thambuttegama",
  ],
  Polonnaruwa: [
    "Polonnaruwa",
    "Kaduruwela",
    "Medirigiriya",
    "Hingurakgoda",
    "Minneriya",
  ],
  Badulla: ["Badulla", "Bandarawela", "Hali-Ela", "Passara", "Welimada"],
  Monaragala: [
    "Monaragala",
    "Wellawaya",
    "Bibile",
    "Buttala",
    "Siyambalanduwa",
  ],
  Ratnapura: [
    "Ratnapura",
    "Balangoda",
    "Embilipitiya",
    "Kuruwita",
    "Pelmadulla",
  ],
  Kegalle: ["Kegalle", "Mawanella", "Warakapola", "Rambukkana", "Yatiyantota"],
};
